blog/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views as BlogViews

app_name = 'blog'

urlpatterns = [
    path('', BlogViews.Index().index, name='Index'),
    path('archives/', BlogViews.Archives, name='Archives'),
    path('tutorial/', BlogViews.Tutorial, name='Tutorial'),
    path('about/', BlogViews.About, name='About'),
    path('project/', BlogViews.Project, name='Project'),


    path('tags/<tag>/', BlogViews.Index().tags, name='tags'),
    path('post/<int:pk>/', BlogViews.Detail, name='post'),
    path('content.json/', BlogViews.search, name='search'),




]

comment/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from .views import CommentView


app_name = 'comment'

urlpatterns = [
    # 发表评论
    path('post-comment/<int:post_id>/', CommentView.as_view(), name='post_comment'),
]

djangoProject2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),

    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'djangoProject2.views.page_not_found'
handler500 = 'djangoProject2.views.server_error'

blog/models.py
# -*- coding:utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
from django.db.models import Q


# Create your models here.
class Tag(models.Model):
    # 文章标签,继承 model.Model
    name = models.CharField(max_length=100, unique=True, verbose_name=u'标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'标签'
        verbose_name_plural = u'标签'


class Tutorial(models.Model):
    name = models.CharField(max_length=100, unique=True, verbose_name=u'教程')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'教程'
        verbose_name_plural = u'教程'


# 普通博文
class Post(models.Model):
    # 文章类型
    post_type = models.CharField(
        max_length=20,
        choices=(('post', u'博客文章'), ('about', u'关于本站'), ('project', u'我的项目')),
        default='post',
        verbose_name=u'类型'
    )

    title = models.CharField(max_length=100, verbose_name=u'标题')
    body = RichTextUploadingField(verbose_name=u'正文')
    created_time = models.DateTimeField(verbose_name=u'创建时间')
    modified_time = models.DateTimeField(auto_now=True, verbose_name=u'更新时间')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name=u'标签')  # 文章标签：一篇文章可以有多个标签，一对多关系，可为空
    tutorial = models.ForeignKey('Tutorial', null=True, blank=True, on_delete=models.SET_NULL,
                                 verbose_name=u'教程')  # 文章教程: 允许为空
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=u'作者')   # 文章作者：一篇文章只有一个作者，与文章一对一关系
    views = models.PositiveIntegerField(default=0, verbose_name=u'访问量')  # 文章访问量
    is_top = models.BooleanField(default=False, verbose_name=u'顶置文章')  # 文章是否顶置，默认不顶置
    is_show = models.BooleanField(default=True, verbose_name=u'发布状态')    # 文章发布状态，默认是创建成功就发布

    def get_next_field_by_created_time(self):  # 获取下一页
        post = Post.objects.filter(~Q(pk=self.pk), is_show=True, post_type='post',
                                   created_time__gte=self.created_time).order_by('created_time').first()
        return post

    def get_previous_field_by_created_time(self):
        post = Post.objects.filter(~Q(pk=self.pk), is_show=True, post_type='post',
                                   created_time__lte=self.created_time).order_by('-created_time').first()
        return post

    def __str__(self):
        return self.title

    # 自定义 get_absolute_url 方法
    def get_absolute_url(self):
        return reverse('blog:post', kwargs={'pk': self.pk})

    # 自定义 increase_views 方法：用于统计访问量
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        # 获取 Post 列表时，按照顶置文章、创建时间排序
        ordering = ['-is_top', '-created_time']
        verbose_name = u'博客文章'
        verbose_name_plural = u'博客文章'


# 友情链接
class Links(models.Model):
    name = models.CharField(max_length=100, verbose_name=u'站点名称')
    url = models.URLField(max_length=225, verbose_name=u'站点链接')
    is_show = models.BooleanField(default=True, verbose_name=u'是否展示')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = u'友情链接'
        verbose_name_plural = u'友情链接'


# 广告链接
class Advertising(models.Model):
    ad_name = models.CharField(max_length=100, verbose_name=u'广告名称')
    ad_url = models.URLField(max_length=225, verbose_name=u'广告链接')
    img_url = models.ImageField(upload_to='ad/', verbose_name='广告图片')
    is_show = models.BooleanField(default=True, verbose_name=u'是否推广')

    def __str__(self):
        return self.ad_name

    class Meta:
        verbose_name = u'广告链接'
        verbose_name_plural = u'广告链接'


# 侧边栏 - 音乐插件配置
class SidebarMusic(models.Model):
    server = models.CharField(
        max_length=20,
        choices=(('netease', u'网易云音乐'), ('tencent', u'QQ音乐'), ('xiami', u'虾米'), ('kugou', u'酷狗')),
        unique=True,
        default='netease',
        verbose_name=u'平台'
    )
    mode = models.CharField(
        max_length=20,
        choices=(('random', u'随机'), ('single', u'单曲'), ('circulation', u'列表循环'), ('order', u'列表')),
        default='random',
        verbose_name=u'播放模式'
    )
    type = models.CharField(
        max_length=20,
        choices=(('song', u'单曲'), ('album', u'专辑'), ('playlist', u'歌单'), ('search', u'搜索')),
        default='playlist',
        verbose_name=u'类型'
    )
    # 播放歌单id，获取方法自行百度。比如我的id就是链接后面的id，https://music.163.com/#/playlist?id=2700450552
    play_id = models.BigIntegerField(verbose_name=u'播放歌单id')
    home_url = models.URLField(null=True, blank=True, max_length=225, verbose_name=u'音乐主页')
    autoplay = models.BooleanField(default=True, verbose_name=u'自动播放')
    enable = models.BooleanField(default=True, verbose_name=u'启用插件')

    def __str__(self):
        return self.server

    class Meta:
        verbose_name = u'侧边栏音乐配置'
        verbose_name_plural = u'侧边栏音乐配置'


# 站点设置
class SiteSettings(models.Model):
    name = models.CharField(
        max_length=20,
        choices=(
            ('sitename', u'站点名称'),
            ('sitetitle', u'站点标题'),
            ('email', u'我的邮箱'),
            ('weibo', u'微博主页'),
            ('music', u'我的音乐主页'),
            ('twitter', u'Twitter'),
            ('github', u'GitHub'),
            ('beian', u'备案号'),
            ('baidu_tj', u'百度统计代码'),
        ),
        unique=True,
        verbose_name=u'名称'
    )
    value = models.TextField(verbose_name=u'值')
    is_show = models.BooleanField(default=True, verbose_name=u'是否展示')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-name']
        verbose_name = u'站点设置'
        verbose_name_plural = u'站点设置'

comment/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

blog/views.py
# _*_ coding:utf-8 _*_

from django.shortcuts import render, get_object_or_404
from blog.models import Post
from comment.models import Comment
from comment.forms import CommentForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
import json
from django.http import HttpResponse
from djangoProject2.views import page_not_found


# 获取某篇文章的评论回复内容
def comment_reply_content(post_id):
    # 评论
    comments = Comment.objects.filter(is_show=True, post_id=post_id, comment_type='comment').order_by('pk')
    comments_dict = {'comments': {}, 'count': 0}
    for comment in comments:
        comments_dict['comments'][comment.id] = {
            'comment': {
                'id': comment.pk,
                'post_id': comment.post_id,
                'add_time': comment.add_time,
                'content': comment.content,
                'parent_id': comment.parent_id,
                'reply_id': comment.reply_id,
                'nick': comment.nick,
                'browser': comment.browser,
                'client': comment.client,
                'avatar': comment.avatar,
            },
            'reply': [],
        }
    # 回复
    replys = Comment.objects.filter(is_show=True, post_id=post_id, comment_type='reply').order_by('pk')
    for reply in replys:
        if reply.parent_id in comments_dict['comments'].keys():
            comments_dict['comments'][reply.parent_id]['reply'].append({
                'id': reply.pk,
                'post_id': reply.post_id,
                'add_time': reply.add_time,
                'content': reply.content,
                'parent_id': reply.parent_id,
                'reply_id': reply.reply_id,
                'nick': reply.nick,
                'to_nick': reply.to_nick,
                'browser': reply.browser,
                'client': reply.client,
                'avatar': reply.avatar,
            })
    comments_dict['count'] = len(replys) + len(comments)
    return comments_dict


# 博客文章列表页面
class Index(object):
    def __init__(self):
        # 定义 per_page 的值，每个页面的文章数
        self.per_page = 10

    def index(self, request):
        # 博客首页：获取Post表中所有文章列表
        post_list = Post.objects.filter(is_show=True, post_type='post')
        page = request.GET.get('page')
        return self.get_data(post_list=post_list, page=page, request=request)

    def tags(self, request, tag):
        # 标签：按照标签(tag)查询Post表中的文章列表
        post_list = Post.objects.filter(tags__name=tag, is_show=True, post_type='post')
        page = request.GET.get('page')
        return self.get_data(post_list=post_list, page=page, request=request)

    def get_data(self, post_list, page, request):
        post_list = self.Pagination(post_list=post_list, page=page)
        post_type = 'post'
        return render(request, 'blog/index.html', context={'post_list': post_list, 'post_type': post_type})

    # 高级分页扩展函数
    def Pagination(self, post_list, page):
        # 使用 Paginator 函数将post_list以每页per_page篇文章进行分页
        paginator = Paginator(post_list, self.per_page)
        try:
            post_list = paginator.page(page)
        except PageNotAnInteger:
            post_list = paginator.page(1)
        except EmptyPage:
            post_list = paginator.page(paginator.num_pages)
        return post_list


# 博客详情页
def Detail(request, pk):
    post = get_object_or_404(Post, pk=pk, is_show=True, post_type='post')
    post.increase_views()  # 调用 increase_views 方法，统计访问量
    comments_dict = comment_reply_content(post_id=pk)  # 评论回复
    comment_form = CommentForm()  # 引入评论表单
    context = {
        'post': post,
        'comments_dict': comments_dict,
        'comment_form': comment_form,
    }
    return render(request, 'blog/detail.html', context=context)


# 教程
def Tutorial(request):
    # 获取教程类型博文列表
    post_list = Post.objects.filter(is_show=True, post_type='post', tutorial__name__isnull=False).order_by(
        'created_time')

    # 创建一个 dict, 以教程名称为关键字保存
    post_dict = {}
    for post in post_list:
        if post.tutorial not in post_dict.keys():
            post_dict[post.tutorial] = []
        post_dict[post.tutorial].append(post)
    return render(request, 'blog/tutorials.html', context={'post_dict': post_dict})


# 归档页面
def Archives(request):
    years = Post.objects.filter(is_show=True, post_type='post').dates('created_time', 'year', order='DESC')
    post_list = Post.objects.filter(is_show=True, post_type='post').order_by('-created_time')
    return render(request, 'blog/archives.html', context={'years': years, 'post_list': post_list})


# 关于页面
def About(request):
    post = Post.objects.filter(is_show=True, post_type='about').first()
    if post:
        post.increase_views()  # 调用 increase_views 方法，统计访问量
        comments_dict = comment_reply_content(post_id=post.id)  # 评论回复
        comment_form = CommentForm()  # 引入评论表单
        context = {
            'post': post,
            'comments_dict': comments_dict,
            'comment_form': comment_form,
        }
        return render(request, 'blog/about.html', context=context)
    else:
        return page_not_found(request)


# 我的项目
def Project(request):
    post = Post.objects.filter(is_show=True, post_type='project').first()
    if post:
        post.increase_views()  # 调用 increase_views 方法，统计访问量
        comments_dict = comment_reply_content(post_id=post.id)  # 评论回复
        comment_form = CommentForm()  # 引入评论表单
        context = {
            'post': post,
            'comments_dict': comments_dict,
            'comment_form': comment_form,
        }
        return render(request, 'blog/project.html', context=context)
    else:
        return page_not_found(request)


# 搜索请求
def search(request):
    # 搜索内容
    if request.method == 'GET':
        q = request.GET.get('q')
        post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q), is_show=True, post_type='post')

        data = {'posts': []}
        for post in post_list:
            data['posts'].append({
                "title": post.title,
                "permalink": post.get_absolute_url(),
                "text": post.body
            }, )
        return HttpResponse(json.dumps(data, ensure_ascii=False), content_type="application/json,charset=utf-8")
    else:
        pass

comment/views.py
# -*- coding: utf-8 -*-

from comment.models import Comment
from django.shortcuts import redirect
from django.views import View
from django.core.mail import EmailMultiAlternatives
import re
from djangoProject2.settings import EMAIL_RECEIVE_LIST, EMAIL_HOST_USER


class CommentView(View):
    #  处理POST请求
    def post(self, request, post_id):
        comment = Comment()  # 实例化类
        comment.post_id = post_id
        comment.parent_id = request.POST['parent_id']
        comment.reply_id = request.POST['reply_id']
        comment.nick = request.POST['nick']
        comment.mail = request.POST['mail']
        comment.content = request.POST['content']

        ua = parse_user_agent(request.META.get('HTTP_USER_AGENT', ''))  # 解析HTTP_USER_AGENT
        comment.browser = ua['browser']
        comment.client = ua['client']

        # 处理回复评论
        if request.POST['reply_id'] != '0':
            comment.comment_type = 'reply'
            reply_comment = Comment.objects.filter(id=request.POST['reply_id']).first()
            if reply_comment:
                comment.to_nick = reply_comment.nick
                comment.to_mail = reply_comment.mail

                # 如果是回复评论，则发送邮件通知相关评论人
                recipient_list = EMAIL_RECEIVE_LIST + [reply_comment.mail]
            else:
                recipient_list = None
        else:
            # 如果是新的评论内容，则只需要发送通知博客作者
            recipient_list = EMAIL_RECEIVE_LIST

        comment.save()  # 保存评论数据到数据库

        redirect_url = request.POST['redirect_url'] + '#comment-{0}'.format(comment.id)
        if recipient_list:  # 发送邮件
            try:
                send_email(url=redirect_url, recipient_list=recipient_list, post_id=post_id)
            except BaseException as e:
                print('发送邮件错误: {}'.format(e))
        return redirect(redirect_url)  # 重定向到指定页面

    def get(self, request):
        pass


def send_email(url, recipient_list, post_id):
    """
    发送邮件
    :param url: 评论内容链接
    :param recipient_list: 邮件接收人
    :return: None
    """
    subject = '来自博客的留言'  # 邮件主题
    html_content = '<p>你好，你在博客中的留言有了新的回复内容! <a href="{0}" target="_blank">点击查看</a></p>'.format(url)  # 邮件正文
    msg = EmailMultiAlternatives(
        subject=subject,
        body=html_content,
        from_email=EMAIL_HOST_USER,
        to=recipient_list
    )

    msg.attach_alternative(html_content, "text/html")
    msg.send()  # 发送


# 解析User-Agent
def parse_user_agent(user_agent):
    browser = re.findall(r'([a-z]+/[0-9\.]+)[a-z ]*Safari/[0-9\.]+$', user_agent, re.I)
    if browser:
        browser = browser[0]

    else:
        browser = 'Unknown Browser'

    client = re.findall(r'^[a-z]+/\d*.?\d* \((.*?)\)', user_agent, re.I)
    if client:
        client = client[0]
    else:
        client = 'Unknown Client'

    return {
        'browser': browser,
        'client': client
    }

templates/blog/archives.html
{% extends 'blog/base.html' %}


{% block title %}{{ SITE_CONFIGS.sitename }} - 所有归档{% endblock %}

{% block l_main %}
<div class="l_main">
    <article id="archive-page" class="post article white-box">
        <section class="archive">
        {% for year in years %}
            <div class="archive-item archive-year mark"><h2>{{ year.year }}</h2><hr></div>
            {% for post in post_list %}
                {% if year.year == post.created_time.year %}
                <div class="archive-item archive-post mark">
                    <a href="{{ post.get_absolute_url }}">
                        <time>{{ post.created_time | date:'m-d' }}</time>
                        <span class="title">{{ post.title }}</span>
                    </a>
                </div>
                {% endif %}
            {% endfor %}

        {% empty %}
            找不到任何文章!
        {% endfor %}
        </section>
    </article>
</div>


{% endblock %}

templates/blog/aside.html
{% load static %}
{% load blog_tags %}
{% get_site_configs as SITE_CONFIGS %}

<aside class="l_side">

    <!-- 侧边栏用户插件 -->
    <section class="author">
        <div class="content pure">
            <div class="avatar"><img class="avatar" src="{% static 'images/avatar.png' %}"></div>
            <div class="text">
                <p><span id="jinrishici-sentence">台上凭栏干，犹怯春寒。</span></p>
                <script src="{% static 'js/jinrishici.js' %}" charset="utf-8"></script>
            </div>
            <div class="social-wrapper">
                <a href="mailto:{{ SITE_CONFIGS.email }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external"><i class="social fas fa-envelope" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.github }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fab fa-github" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.weibo }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fab fa-weibo" aria-hidden="true"></i></a>
                <a href="{{ SITE_CONFIGS.music }}" class="social flat-btn waves-effect waves-button" target="_blank" rel="external nofollow noopener noreferrer"><i class="social fas fa-headphones-alt" aria-hidden="true"></i></a>
            </div>
        </div>
    </section>


    <!-- 文章目录 -->
    <section class="toc-wrapper">
        <header class="pure toc-show-hide">
            <div><i id="toc-icon" class="fas fa-caret-down fa-fw" aria-hidden="true"></i>文章目录</div>
        </header>
        <div class="content pure" id="toc-content">
            <ol class="toc"></ol>
        </div>
    </section>

    <!-- 侧边栏广告栏插件 -->
    <section class="plain">
        <header class="pure">
            <div><i class="fas fa-bullhorn fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;广告位!</div>
        </header>

        <div class="content pure">
            {% get_advertising as advertising %}
            {% for ad in advertising %}
            <a title="{{ ad.ad_name }}" href="{{ ad.ad_url }}" target="_blank"><img width="100%" src="{{ ad.img_url.url }}"></a>
            {% endfor %}
        </div>

    </section>

    <!-- 侧边栏热门标签插件 -->
    <section class="tagcloud">
        <header class="pure"><div><i class="fas fa-tags fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;热门标签</div></header>
        <div class="content pure">
            {% get_tags as tags_list %}
            {% for tag in tags_list.tags %}
            <a href="{% url 'blog:tags' tag.name %}" style="" title="{{ tag.num_posts }}个话题">{{ tag.name }}({{ tag.num_posts }})</a>
            {% empty %}
                <a></a>
            {% endfor %}
        </div>
    </section>

    <!-- 侧边栏友情链接插件 -->
    <section class="list">
        <header class="pure"><div><i class="fas fa-medal fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;友情链接</div></header>
        <div class="content pure">
            <ul class="entry">
                {% get_links as links %}
                {% for link in links %}
                <li><a class="flat-box waves-effect waves-block" title="{{ link.name }}" href="{{ link.url }}" target="_blank"><div class="name"><i class="fas fa-link fa-fw" aria-hidden="true"></i> &nbsp;&nbsp;{{ link.name }}</div></a></li>
                {% empty %}
                <li><a class="flat-box waves-effect waves-block" title="" href="{% url 'blog:About' %}"><div class="name"><i class="fas fa-comment-dots fa-fw" aria-hidden="true"></i> &nbsp;&nbsp;暂无友链，互换友链请留言我!</div></a></li>
                {% endfor %}
            </ul>
        </div>
    </section>

    <!-- 侧边栏音乐插件 -->
    {% get_music as music %}
    {% if music %}
    <section class="music">
        <header class="pure">
            <div><i class="fas fa-compact-disc fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;最近在听</div>
            <a class="rightBtn" target="_blank" rel="external nofollow noopener noreferrer" href="{{ music.home_url }}" title="{{ music.home_url }}"><i class="far fa-heart fa-fw"></i></a>
        </header>
        <div class="content pure">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.css">
            <div class="aplayer" {% if music.autoplay %}data-autoplay="true"{% endif %} data-theme="#1BCDFC" data-mode="{{ music.mode }}" data-server="{{ music.server }}" data-type="{{ music.type }}" data-id="{{ music.play_id }}" data-volume="0.7"></div>
            <script src="https://cdn.jsdelivr.net/npm/aplayer@1.7.0/dist/APlayer.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/meting@1.1.0/dist/Meting.min.js"></script>
        </div>
    </section>
    {% endif %}
</aside>
<script src="{% static 'js/aside.js' %}"></script>

templates/blog/header.html
<div id="loading-bar-wrapper" style="display: none;">
    <div id="loading-bar" class="pure" style="width: 100%;"></div>
</div>
<script>setLoadingBarProgress(20)</script>
<header class="l_header pure">
    <div class="wrapper">
        <div class="nav-main container container--flex">
            <a class="logo flat-box waves-effect waves-block" href="{% url 'blog:Index' %}">{{ SITE_CONFIGS.sitename }}'s Blog</a>
            <div class="menu">
                <ul class="h-list">
                    <li><a id="home" class="nav flat-box waves-effect waves-block" href="{% url 'home' %}"><i class="fas fa-home fa-fw"></i>&nbsp;主页</a></li>
                    <li><a id="blog" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Index' %}"><i class="fas fa-rss fa-fw"></i>&nbsp;博客</a></li>
                    <li><a id="blogtutorial" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Tutorial' %}"><i class="fas fa-book fa-fw"></i>教程</a></li>
                    <li><a id="blogarchives" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Archives' %}"><i class="fas fa-archive fa-fw"></i>&nbsp;归档</a></li>
                    <li><a id="blogproject" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Project' %}"><i class="fas fa-flask fa-fw"></i>&nbsp;项目</a></li>
                    <li><a id="blogabout" class="nav flat-box waves-effect waves-block" href="{% url 'blog:About' %}"><i class="fas fa-user fa-fw"></i>&nbsp;关于</a></li>
                </ul>
            </div>
            <div class="m_search">
                <form name="searchform" class="form u-search-form">
                    <input type="text" class="input u-search-input" placeholder="搜索">
                    <span class="icon"><i class="fas fa-search fa-fw"></i></span>
                </form>
            </div>
            <ul class="switcher h-list">
                <li class="s-search"><a class="fas fa-search fa-fw" href="javascript:void(0)"></a></li>
                <li class="s-menu"><a class="fas fa-bars fa-fw" href="javascript:void(0)"></a></li>
            </ul>
        </div>

        <div class="nav-sub container container--flex">
            <a class="logo flat-box waves-effect waves-block"></a>
            <ul class="switcher h-list">
                <li class="s-comment"><a class="flat-btn fas fa-comments fa-fw waves-effect waves-button" href="javascript:void(0)"></a></li>
                <li class="s-toc"><a class="flat-btn fas fa-list fa-fw waves-effect waves-button" href="javascript:void(0)"></a></li>
            </ul>
        </div>
    </div>
</header>
<aside class="menu-phone">
    <header>
        <nav class="menu">
            <ul>
                <li><a id="home" class="nav flat-box waves-effect waves-block" href="{% url 'home' %}"><i class="fas fa-home fa-fw"></i>&nbsp;主页</a></li>
                <li><a id="blog" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Index' %}"><i class="fas fa-rss fa-fw"></i>&nbsp;博客</a></li>
                <li><a id="blogtutorial" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Tutorial' %}"><i class="fas fa-book fa-fw"></i>教程</a></li>
                <li><a id="blogarchives" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Archives' %}"><i class="fas fa-archive fa-fw"></i>&nbsp;归档</a></li>
                <li><a id="blogproject" class="nav flat-box waves-effect waves-block" href="{% url 'blog:Project' %}"><i class="fas fa-flask fa-fw"></i>&nbsp;项目</a></li>
                <li><a id="blogabout" class="nav flat-box waves-effect waves-block" href="{% url 'blog:About' %}"><i class="fas fa-user fa-fw"></i>&nbsp;关于</a></li>
            </ul>
        </nav>
    </header>
</aside>

templates/blog/tags.html
{% extends 'blog/base.html' %}


{% block title %}{{ SITE_CONFIGS.sitename }} - 所有标签{% endblock %}

{% block l_main %}
<div class="l_main">
    <section class="post-list">
        <div class="post-wrapper">
            <article id="archive-page" class="post article white-box">
                <section class="archive">
                    <div class="archive-item archive-year mark"><h2>所有标签</h2><hr></div>
                    <div class="archive-item archive-post mark">
                        {% for tag in tags %}
                        <a href="{% url 'blog:tags' tag.name %}"><time><i class="fas fa-tag fa-fw" aria-hidden="true"></i>&nbsp;&nbsp;{{ tag.name }}</time> <span class="title">({{ tag.num_posts }}) </span></a>

                        {% endfor %}
                    </div>
                    <br>
                </section>
            </article>
        </div>
    </section>
</div>


{% endblock %}